### ISSUE TITLE
Remove countries that are not in ISO-3166 

### ISSUE THREAD

**Issue by ilyabreev** [ilyabreev/Bia.Countries#11]
This project is not intended to include countries that are not part of ISO-3166.
They contain dummy `XX` alpha-2 code.
It's wrong and they are need to be removed.

**Comment by KeeperB5** [comment]
The "countries" indeed do not exist in the official ISO-3166 spec. Those were included for compatibility with Microsoft Active Directory. The alpha2 codes were "XX" on purpose because that is what Active Directory assigns to alpha2 when one of these is selected.

I wanted this project be usable by Windows sysadmins who work with Active Directory, which is also the reason why I made the PowerShell module that uses Bia.Countries. I would prefer this commit to be reverted. Otherwise I'd have to maintain my own fork of Bia.Countries.

**Comment by ilyabreev** [comment]
Sorry for misunderstanding the "XX". I think we could find another way of
maintaining these countries that are not in ISO.
We must clearly separate methods that work with ISO subset of data and then
extend it with ActiveX data.
What do you think about it?
пн, 19 июня 2017 г. в 20:38, Juho Lehto <notifications@github.com>:

**Comment by KeeperB5** [comment]
I'll try to think something and propose a solution. Unfortunately life has kept me busy lately, but I'll try to get it done next week.

**Comment by ilyabreev** [comment]
Yeah, I'll think on it also.

ср, 21 июн. 2017 г. в 10:42, Juho Lehto <notifications@github.com>:
